### ISSUE TITLE
Dynamic routing refresh -> back to rules results in 404

### ISSUE THREAD

**Issue by Abaddon16** [Stephen-Fredrickson/The-Goblin-Society#4]
Bug

How to reproduce:

1. Pathfinder 1st Edition
2. Rules
  a. Notice URL is: https://www.thegoblinsociety.com/pathfinder1e/rules
3. Dwarves -> Explore
  a. Notice URL is: https://www.thegoblinsociety.com/pathfinder1e/races/Dwarves
4. Refresh (F5)
  a. Notice URL has changed to: https://www.thegoblinsociety.com/pathfinder1e/races/dwarves/
5. Back to Rules
  a. Notice URL is now: https://www.thegoblinsociety.com/pathfinder1e/races/rules
  b. Should be: https://www.thegoblinsociety.com/pathfinder1e/rules

Suggested fix:

1. Correct Vue route to be https://www.thegoblinsociety.com/pathfinder1e/rules

**Comment by Stephen-Fredrickson** [comment]
The above v-bind needs to be added to any buttons that navigate. This will overwrite the route produced on refresh.

![routing](https://user-images.githubusercontent.com/54752422/71672265-195bfa00-2d3b-11ea-9beb-1689e71e317d.png)
